ci: Pin docker image to ubuntu 20.04 (#8126)
Summary:
Using `latest` points to 20.10 has reached end of life causing Docker build to fail on main:
```
Step 2/9 : RUN apt-get update && apt-get install -y   build-essential   ca-certificates   clang   curl   git   libelf-dev   libncursesw5-dev   libssl-dev   m4   pkg-config   python3   zlib1g-dev
 ---> Running in f9b246bed291
Ign:1 http://security.ubuntu.com/ubuntu groovy-security InRelease
Err:2 http://security.ubuntu.com/ubuntu groovy-security Release
  404  Not Found [IP: 91.189.91.39 80]
Ign:3 http://archive.ubuntu.com/ubuntu groovy InRelease
Ign:4 http://archive.ubuntu.com/ubuntu groovy-updates InRelease
Ign:5 http://archive.ubuntu.com/ubuntu groovy-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu groovy Release
  404  Not Found [IP: 91.189.88.142 80]
Err:7 http://archive.ubuntu.com/ubuntu groovy-updates Release
  404  Not Found [IP: 91.189.88.142 80]
Err:8 http://archive.ubuntu.com/ubuntu groovy-backports Release
  404  Not Found [IP: 91.189.88.142 80]
Reading package lists...
E: The repository 'http://security.ubuntu.com/ubuntu groovy-security Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu groovy Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu groovy-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu groovy-backports Release' does not have a Release file.
The command '/bin/sh -c apt-get update && apt-get install -y   build-essential   ca-certificates   clang   curl   git   libelf-dev   libncursesw5-dev   libssl-dev   m4   pkg-config   python3   zlib1g-dev' returned a non-zero code: 100
```

This at least makes it run (see PR), but rust build fails. Will follow up with commit to fix that.

```
error[E0432]: unresolved import `nix`
  --> below/procfs/src/lib.rs:16:5
   |
16 | use nix::sys;
   |     ^^^ use of undeclared crate or module `nix`
```
(probably caused by latest changes to procfs for disk usage)

Pull Request resolved: https://github.com/facebookincubator/below/pull/8126

Test Plan: CI

Reviewed By: lnyng

Differential Revision: D33411684

Pulled By: brianc118

fbshipit-source-id: 95c898c4b5ce9728808b45a99e977283a19ef28f